"""
Step 1: Run this FIRST to generate your Polymarket API credentials.
=========================================================================
Usage:
    python setup_keys.py

It will:
  1. Connect to Polymarket CLOB
  2. Derive your API key, secret, and passphrase from your private key
  3. Test the connection
  4. Save everything to keys.env
"""
import os
import sys

try:
    from py_clob_client.client import ClobClient
except ImportError:
    print("[ERROR] py-clob-client not installed.")
    print("  Run: pip install py-clob-client==0.34.5 web3==6.14.0 python-dotenv requests numpy")
    sys.exit(1)

HOST = "https://clob.polymarket.com"
CHAIN_ID = 137

def main():
    print("=" * 60)
    print("  Polymarket API Key Setup")
    print("=" * 60)

    # --- Get private key ---
    pk = os.getenv("POLY_PRIVATE_KEY", "").strip()
    if not pk:
        pk = input("\nEnter your Polymarket private key\n(from https://reveal.polymarket.com, WITHOUT 0x prefix):\n> ").strip()

    if pk.startswith("0x"):
        pk = pk[2:]
        print("[INFO] Removed '0x' prefix from key.")

    if len(pk) != 64:
        print(f"[WARN] Key length is {len(pk)}, expected 64 hex chars. Continuing anyway...")

    # --- Get login method ---
    print("\nHow do you log into Polymarket?")
    print("  1 = Email (Magic link)")
    print("  2 = Browser wallet (MetaMask, Coinbase Wallet)")
    print("  0 = Direct EOA (no proxy)")
    sig_type_str = input("Enter 0, 1, or 2 [default=1]: ").strip() or "1"
    sig_type = int(sig_type_str)

    # --- Get funder address (required for sig_type 1 and 2) ---
    funder = ""
    if sig_type in (1, 2):
        funder = os.getenv("POLY_FUNDER_ADDRESS", "").strip()
        if not funder:
            print("\nEnter your Polymarket deposit/proxy address.")
            print("Find it at: polymarket.com/settings -> Deposit Address")
            print("This is NOT your MetaMask address (for email logins).")
            funder = input("> ").strip()

    # --- Initialize client ---
    print("\n[...] Connecting to Polymarket CLOB...")

    try:
        if sig_type in (1, 2) and funder:
            client = ClobClient(
                HOST, key=pk, chain_id=CHAIN_ID,
                signature_type=sig_type, funder=funder
            )
        else:
            client = ClobClient(HOST, key=pk, chain_id=CHAIN_ID)

        # Test basic connection
        ok = client.get_ok()
        print(f"[OK] Server connection: {ok}")

        server_time = client.get_server_time()
        print(f"[OK] Server time: {server_time}")

    except Exception as e:
        print(f"[FAIL] Connection failed: {e}")
        sys.exit(1)

    # --- Derive API credentials ---
    print("\n[...] Deriving API credentials from your private key...")

    try:
        api_creds = client.create_or_derive_api_creds()
        api_key = api_creds.api_key
        api_secret = api_creds.api_secret
        api_passphrase = api_creds.api_passphrase

        print(f"[OK] API Key:      {api_key}")
        print(f"[OK] Secret:       {api_secret[:10]}...{api_secret[-4:]}")
        print(f"[OK] Passphrase:   {api_passphrase[:10]}...{api_passphrase[-4:]}")

    except Exception as e:
        print(f"[FAIL] Could not derive API credentials: {e}")
        print("\nPossible fixes:")
        print("  - Make sure your private key is correct")
        print("  - Make sure your funder address is your POLYMARKET deposit address")
        print("  - Try sig_type=0 if you use MetaMask directly")
        sys.exit(1)

    # --- Set creds and test authenticated endpoint ---
    print("\n[...] Testing authenticated access...")

    try:
        client.set_api_creds(api_creds)
        orders = client.get_orders()
        print(f"[OK] Authenticated! Found {len(orders) if orders else 0} existing orders.")
    except Exception as e:
        print(f"[WARN] Auth test returned: {e}")
        print("  This may be OK if you have no open orders.")

    # --- Save to keys.env ---
    env_content = f"""# Polymarket Bot Credentials
# Generated by setup_keys.py - DO NOT share this file!
# ===================================================

# Private key (without 0x prefix)
PK={pk}

# Polymarket proxy/deposit address (funder)
FUNDER={funder}

# Signature type (0=EOA, 1=Email/Magic, 2=Browser wallet)
SIG_TYPE={sig_type}

# API credentials (derived from private key)
CLOB_API_KEY={api_key}
CLOB_API_SECRET={api_secret}
CLOB_API_PASSPHRASE={api_passphrase}

# Bot settings
FUND=150.0
RISK_PCT=0.10
DRY_RUN=true
"""

    with open("keys.env", "w") as f:
        f.write(env_content)

    print(f"\n[OK] Saved credentials to keys.env")
    print("\n" + "=" * 60)
    print("  SETUP COMPLETE!")
    print("=" * 60)
    print("\nNext steps:")
    print("  1. python test_connection.py   (verify everything works)")
    print("  2. python bot.py               (start dry-run trading)")
    print("  3. Edit keys.env -> DRY_RUN=false  (go live when ready)")
    print()


if __name__ == "__main__":
    main()
